#!/usr/bin/python

import os
import sys
import subprocess as sp

thisdir = os.path.dirname(os.path.realpath(__file__))
td = os.path.realpath(thisdir + "/../..")
sys.path.append(td)

from ptest_utils import *

os.system("mkdir -p " + thisdir + "/taint2_logs")
os.system("rm " + thisdir+"/taint2_logs/*")

run_test_debian("-panda taint2 ", 'cde',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_e")

run_test_debian("-panda taint2 ", 'cdad',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_ad")
run_test_debian("-panda taint2 ", 'cdaf',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_af")
run_test_debian("-panda taint2 ", 'cdau8',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_au8")
run_test_debian("-panda taint2 ", 'cdau16',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_au16")
run_test_debian("-panda taint2 ", 'cdau32',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_au32")
run_test_debian("-panda taint2 ", 'cdau64',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_au64")
run_test_debian("-panda taint2 ", 'cdas8',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_as8")
run_test_debian("-panda taint2 ", 'cdas16',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_as16")
run_test_debian("-panda taint2 ", 'cdas32',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_as32")
run_test_debian("-panda taint2 ", 'cdas64',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_as64")

run_test_debian("-panda taint2 ", 'cdsd',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_sd")
run_test_debian("-panda taint2 ", 'cdsf',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_sf")
run_test_debian("-panda taint2 ", 'cdsu8',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_su8")
run_test_debian("-panda taint2 ", 'cdsu16',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_su16")
run_test_debian("-panda taint2 ", 'cdsu32',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_su32")
run_test_debian("-panda taint2 ", 'cdsu64',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_su64")
run_test_debian("-panda taint2 ", 'cdss8',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_ss8")
run_test_debian("-panda taint2 ", 'cdss16',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_ss16")
run_test_debian("-panda taint2 ", 'cdss32',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_ss32")
run_test_debian("-panda taint2 ", 'cdss64',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_ss64")

run_test_debian("-panda taint2 ", 'cdmd',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_md")
run_test_debian("-panda taint2 ", 'cdmf',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_mf")
run_test_debian("-panda taint2 ", 'cdmu8',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_mu8")
run_test_debian("-panda taint2 ", 'cdmu16',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_mu16")
run_test_debian("-panda taint2 ", 'cdmu32',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_mu32")
run_test_debian("-panda taint2 ", 'cdmu64',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_mu64")
run_test_debian("-panda taint2 ", 'cdms8',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_ms8")
run_test_debian("-panda taint2 ", 'cdms16',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_ms16")
run_test_debian("-panda taint2 ", 'cdms32',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_ms32")
run_test_debian("-panda taint2 ", 'cdms64',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_ms64")

run_test_debian("-panda taint2 ", 'cddd',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_dd")
run_test_debian("-panda taint2 ", 'cddf',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_df")
run_test_debian("-panda taint2 ", 'cddu8',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_du8")
run_test_debian("-panda taint2 ", 'cddu16',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_du16")
run_test_debian("-panda taint2 ", 'cddu32',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_du32")
run_test_debian("-panda taint2 ", 'cddu64',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_du64")
run_test_debian("-panda taint2 ", 'cdds8',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_ds8")
run_test_debian("-panda taint2 ", 'cdds16',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_ds16")
run_test_debian("-panda taint2 ", 'cdds32',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_ds32")
run_test_debian("-panda taint2 ", 'cdds64',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_ds64")

run_test_debian("-panda taint2 ", 'cdbwau8',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_bwau8")
run_test_debian("-panda taint2 ", 'cdbwau16',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_bwau16")
run_test_debian("-panda taint2 ", 'cdbwau32',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_bwau32")
run_test_debian("-panda taint2 ", 'cdbwau64',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_bwau64")
run_test_debian("-panda taint2 ", 'cdbwas8',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_bwas8")
run_test_debian("-panda taint2 ", 'cdbwas16',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_bwas16")
run_test_debian("-panda taint2 ", 'cdbwas32',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_bwas32")
run_test_debian("-panda taint2 ", 'cdbwas64',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_bwas64")

run_test_debian("-panda taint2 ", 'cdbwou8',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_bwou8")
run_test_debian("-panda taint2 ", 'cdbwou16',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_bwou16")
run_test_debian("-panda taint2 ", 'cdbwou32',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_bwou32")
run_test_debian("-panda taint2 ", 'cdbwou64',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_bwou64")
run_test_debian("-panda taint2 ", 'cdbwos8',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_bwos8")
run_test_debian("-panda taint2 ", 'cdbwos16',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_bwos16")
run_test_debian("-panda taint2 ", 'cdbwos32',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_bwos32")
run_test_debian("-panda taint2 ", 'cdbwos64',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_bwos64")

run_test_debian("-panda taint2 ", 'cdbwxu8',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_bwxu8")
run_test_debian("-panda taint2 ", 'cdbwxu16',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_bwxu16")
run_test_debian("-panda taint2 ", 'cdbwxu32',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_bwxu32")
run_test_debian("-panda taint2 ", 'cdbwxu64',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_bwxu64")
run_test_debian("-panda taint2 ", 'cdbwxs8',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_bwxs8")
run_test_debian("-panda taint2 ", 'cdbwxs16',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_bwxs16")
run_test_debian("-panda taint2 ", 'cdbwxs32',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_bwxs32")
run_test_debian("-panda taint2 ", 'cdbwxs64',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_bwxs64")

run_test_debian("-panda taint2 ", 'cdbwslu8',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_bwslu8")
run_test_debian("-panda taint2 ", 'cdbwslu16',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_bwslu16")
run_test_debian("-panda taint2 ", 'cdbwslu32',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_bwslu32")
run_test_debian("-panda taint2 ", 'cdbwslu64',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_bwslu64")
run_test_debian("-panda taint2 ", 'cdbwsls8',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_bwsls8")
run_test_debian("-panda taint2 ", 'cdbwsls16',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_bwsls16")
run_test_debian("-panda taint2 ", 'cdbwsls32',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_bwsls32")
run_test_debian("-panda taint2 ", 'cdbwsls64',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_bwsls64")

run_test_debian("-panda taint2 ", 'cdbwsru8',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_bwsru8")
run_test_debian("-panda taint2 ", 'cdbwsru16',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_bwsru16")
run_test_debian("-panda taint2 ", 'cdbwsru32',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_bwsru32")
run_test_debian("-panda taint2 ", 'cdbwsru64',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_bwsru64")
run_test_debian("-panda taint2 ", 'cdbwsrs8',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_bwsrs8")
run_test_debian("-panda taint2 ", 'cdbwsrs16',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_bwsrs16")
run_test_debian("-panda taint2 ", 'cdbwsrs32',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_bwsrs32")
run_test_debian("-panda taint2 ", 'cdbwsrs64',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_bwsrs64")

run_test_debian("-panda taint2 ", 'cdmalloc',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_malloc")

run_test_debian("-panda taint2 ", 'cdmemset',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_memset")

run_test_debian("-panda taint2 ", 'cdmemcpy',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_memcpy")

run_test_debian("-panda taint2 ", 'cd11',"i386")
os.system("mv " + tmpoutdir + "/taint2_log " + thisdir + "/taint2_logs/taint2_log_11")

os.system("mv " + thisdir+"/taint2_logs/* " + tmpoutdir)

os.system("rmdir " + thisdir+"/taint2_logs")

sys.exit(0)
